Return-Path: <qemu-devel-bounces+lists+qemu-devel=lfdr.de@nongnu.org>
X-Original-To: lists+qemu-devel@lfdr.de
Delivered-To: lists+qemu-devel@lfdr.de
Received: from lists.gnu.org (lists.gnu.org [209.51.188.17])
	by mail.lfdr.de (Postfix) with ESMTPS id 134CBAC50A1
	for <lists+qemu-devel@lfdr.de>; Tue, 27 May 2025 16:16:21 +0200 (CEST)
Received: from localhost ([::1] helo=lists1p.gnu.org)
	by lists.gnu.org with esmtp (Exim 4.90_1)
	(envelope-from <qemu-devel-bounces@nongnu.org>)
	id 1uJv5g-0000Z9-0d; Tue, 27 May 2025 10:15:46 -0400
Received: from eggs.gnu.org ([2001:470:142:3::10])
 by lists.gnu.org with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
 (Exim 4.90_1) (envelope-from <maz@kernel.org>)
 id 1uJv5T-0000Wg-MW; Tue, 27 May 2025 10:15:29 -0400
Received: from dfw.source.kernel.org ([2604:1380:4641:c500::1])
 by eggs.gnu.org with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
 (Exim 4.90_1) (envelope-from <maz@kernel.org>)
 id 1uJv5N-00087r-GI; Tue, 27 May 2025 10:15:27 -0400
Received: from smtp.kernel.org (transwarp.subspace.kernel.org [100.75.92.58])
 by dfw.source.kernel.org (Postfix) with ESMTP id 52E3B5C1D0A;
 Tue, 27 May 2025 14:12:55 +0000 (UTC)
Received: by smtp.kernel.org (Postfix) with ESMTPSA id 03B02C4CEE9;
 Tue, 27 May 2025 14:15:12 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
 s=k20201202; t=1748355312;
 bh=g1k9FRzqLORXJS5ACE8FbcuyWdMPc4sfhJTsJPJL9pQ=;
 h=Date:From:To:Cc:Subject:In-Reply-To:References:From;
 b=Q3j0sxotIDFaWBH7OOm8LzulaiGjoGSiB5eTzamONotcD8SuZo/dgw5Lc2HmuPfwV
 AHTZKZQiISaNniK6HucF+Tg4gG3DCEYOzvH2Z4ZmRm+Ty5DmSgPrGwN510PwEvqTeV
 QFQpJGJ40eyUw53pgFDFiAmR5qrgN9LJiIF8BmPaxfM1gg8vQSbHBHX4anS9ASfQK8
 uPGj7+lNO/NB9XklOGzyp/dDnukaO4KgZSZuTTpC+ESM28EBZhEr90tDTt5njdddsu
 Z/Vnq5c5mpw+z4c/81xr2dEZLxca5o7TtH3ESPUi9yPIzcfq78pa/82MCTEVhkjwki
 /R4PylvWeuhmA==
Received: from sofa.misterjones.org ([185.219.108.64]
 helo=goblin-girl.misterjones.org)
 by disco-boy.misterjones.org with esmtpsa (TLS1.3) tls
 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (Exim 4.95)
 (envelope-from <maz@kernel.org>) id 1uJv5B-000tyG-9j;
 Tue, 27 May 2025 15:15:09 +0100
Date: Tue, 27 May 2025 15:15:08 +0100
Message-ID: <86h616dtsj.wl-maz@kernel.org>
From: Marc Zyngier <maz@kernel.org>
To: eric.auger@redhat.com
Cc: Miguel Luis <miguel.luis@oracle.com>,
 "eric.auger.pro@gmail.com" <eric.auger.pro@gmail.com>,
 "qemu-devel@nongnu.org" <qemu-devel@nongnu.org>,
 "qemu-arm@nongnu.org" <qemu-arm@nongnu.org>,
 "peter.maydell@linaro.org" <peter.maydell@linaro.org>,
 "richard.henderson@linaro.org" <richard.henderson@linaro.org>,
 "gkulkarni@amperecomputing.com" <gkulkarni@amperecomputing.com>,
 "gankulkarni@os.amperecomputing.com" <gankulkarni@os.amperecomputing.com>
Subject: Re: [PATCH v5 0/5] ARM Nested Virt Support
In-Reply-To: <ee464d7c-9b77-4aa7-9afa-627e497c7581@redhat.com>
References: <20250527062534.1186004-1-eric.auger@redhat.com>
 <C10D9293-32F7-4834-9CEE-6AFD4BDBC30E@oracle.com>
 <86ldqidzyl.wl-maz@kernel.org>
 <822E77EF-9802-4F16-B8D4-A48F3A624151@oracle.com>
 <ee464d7c-9b77-4aa7-9afa-627e497c7581@redhat.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL-LB/10.8 EasyPG/1.0.0 Emacs/30.1
 (aarch64-unknown-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-SA-Exim-Connect-IP: 185.219.108.64
X-SA-Exim-Rcpt-To: eric.auger@redhat.com, miguel.luis@oracle.com,
 eric.auger.pro@gmail.com, qemu-devel@nongnu.org, qemu-arm@nongnu.org,
 peter.maydell@linaro.org, richard.henderson@linaro.org,
 gkulkarni@amperecomputing.com, gankulkarni@os.amperecomputing.com
X-SA-Exim-Mail-From: maz@kernel.org
X-SA-Exim-Scanned: No (on disco-boy.misterjones.org);
 SAEximRunCond expanded to false
Received-SPF: pass client-ip=2604:1380:4641:c500::1;
 envelope-from=maz@kernel.org; helo=dfw.source.kernel.org
X-Spam_score_int: -49
X-Spam_score: -5.0
X-Spam_bar: -----
X-Spam_report: (-5.0 / 5.0 requ) BAYES_00=-1.9, DKIMWL_WL_HIGH=-2.907,
 DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1, DKIM_VALID_EF=-0.1,
 SPF_HELO_NONE=0.001, SPF_PASS=-0.001 autolearn=ham autolearn_force=no
X-Spam_action: no action
X-BeenThere: qemu-devel@nongnu.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <qemu-devel.nongnu.org>
List-Unsubscribe: <https://lists.nongnu.org/mailman/options/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=unsubscribe>
List-Archive: <https://lists.nongnu.org/archive/html/qemu-devel>
List-Post: <mailto:qemu-devel@nongnu.org>
List-Help: <mailto:qemu-devel-request@nongnu.org?subject=help>
List-Subscribe: <https://lists.nongnu.org/mailman/listinfo/qemu-devel>,
 <mailto:qemu-devel-request@nongnu.org?subject=subscribe>
Errors-To: qemu-devel-bounces+lists+qemu-devel=lfdr.de@nongnu.org
Sender: qemu-devel-bounces+lists+qemu-devel=lfdr.de@nongnu.org

On Tue, 27 May 2025 14:11:41 +0100,
Eric Auger <eric.auger@redhat.com> wrote:
>=20
> Hi Miguel, Marc,
>=20
> On 5/27/25 2:54 PM, Miguel Luis wrote:
> >
> >> On 27 May 2025, at 12:01, Marc Zyngier <maz@kernel.org> wrote:
> >>
> >> On Tue, 27 May 2025 12:33:23 +0100,
> >> Miguel Luis <miguel.luis@oracle.com> wrote:
> >>> Hi Eric,
> >>>
> >>>> On 27 May 2025, at 06:24, Eric Auger <eric.auger@redhat.com> wrote:
> >>>>
> >>>> Now that ARM nested virt has landed in kvm/next, let's turn the seri=
es
> >>>> into a PATCH series. The linux header update was made against kvm/ne=
xt.
> >>>>
> >>>> For gaining virt functionality in KVM accelerated L1, The host needs=
 to
> >>>> be booted with "kvm-arm.mode=3Dnested" option and qemu needs to be i=
nvoked
> >>>> with: -machine virt,virtualization=3Don.
> >>> For the current kvmarm/next the guest also needs
> >>> =E2=80=9Ckvm-arm.mode=3Dnested=E2=80=9D I believe.
> >> No, unless you want the guest itself to be NV-capable.
> Effectively you don't need "kvm-arm.mode=3Dnested" except if you want want
> multiple level of nesting.

You need kvm-arm.mode=3Dnested on the command-line of a kernel that acts
as a host exposing KVM_CAP_ARM_EL2. This is obviously a recursive
property, but that's for the user to decide if they want it or not.

> > Correct, I got carried away with some mode combinations. Maybe we shoul=
d depict
> > here more broadly how NV might be used with different mode combinations=
. I'll
> > think about this further ahead.
> >
> > As far this series go I couldn't found any issue booting a L1 guest with
> > virtualization=3Don and a L2 guest with virtualization=3Doff.
>=20
> on my end I tested with various untouched L2 guests (debian, fed, rhel)
> in 4kB/4kB/4KB page size mode (host, L1, L2). Those configs were successf=
ul.

I'm doing 4/4/4 (x1e) and 16/16/4 (m2). I'm also doing 4/4/4/4/4, but
that's not very reliable yet,

> with 64kB/64kB/64kB configs I am less lucky atm. One one machine I
> cannot boot L1 with virtualization=3Don. On the other I can boot L1 but
> cannot boot L2.

I think x1e supports 64k pages, but I'd need to try. Not exactly the
highest priority on my list of things to debug.

> Trying my best to debug a little bit further with my setup. Anyway if
> somebody else can try 64kB configs, it would help to confirm whether
> there are pending issues. I don't think they are related to this qemu
> integration series though.

Yeah, definitely a kernel issue IMO.

Thanks,

	M.

--=20
Without deviation from the norm, progress is not possible.

